server:
  port: 8087

spring:
  mail:
    host: smtp.gmail.com
    port: 587 #465
    protocol: smtps
    username:
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
    queues:
      registration-mail: registration_mail

service:
  activation:
    uri: http://127.0.0.1:8086/user/activation?id={id}